version: '3.8'
services:
  web:
    image: pitagorassns_api
    ports:
      - '80:80'
    depends_on:
      - pitagorassns_data
  mongodb:
    image: mongo
    container_name: pitagorassns_data
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: